version: "3.9"

services:
  postgres_db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: blog-app
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: app
      POSTGRES_HOST_AUTH: trust
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
